
SIMULATIONS = 300     # 300
ROUNDS = 1000         # 1000

RENT_VALUE = 70
SELL_VALUE =  RENT_VALUE * 2

BOARD_LENGHT = 20
DEFAULT_BALANCE = 300
MAX_LIMIT = 50

# slesp times in minutes
SLEEP_TIME_ZERO = 0
SLEEP_TIME_ONE = 1
SLEEP_TIME_TWO = 2
SLEEP_TIME_THREE = 3
SLEEP_TIME_FOUR = 4
SLEEP_TIME_WALK = 0  # in second . set value 0.7 to see player walking
