


from time import sleep


PROFISSIONAL_FOLDER = '/media/ijdev/DATA/PROFISSIONAL/'
DOWNLOAD_FOLDER_PATH = '/home/ijdev/Downloads/'
VALERIA_PROJECT_FOLDER_PATH = '/media/ijdev/DATA/PROFISSIONAL/VALERIA_FERREIRA_LIMA/'
COMERCIAL_FOLDER = 'COMERCIALFERREIRALIMA'
MAGALU_STORE = 'MAGAZINE_LUIZA'
ODERCO = 'ODERCO'
ODERCO_PATH = VALERIA_PROJECT_FOLDER_PATH + MAGALU_STORE + '/' + ODERCO + '/'
SD_STAGE = '/media/ijdev/DATA/senseData/sc_bin/stage/c93_navita/'
IJG_USAGE = 'IJGeneralUsageLib/IJGeneralUsageLib/libs.py'
SLEEP_TIME = 0
HEADER_PIPE_SEPARATOR = '|'
HEADER_COMMER_SEPARATOR = ','